### ISSUE TITLE
Cant launch applications

### ISSUE THREAD

**Issue by TalkierTick9904** [xremap/nix-flake#56]
Hi! I tried to configure xremap on nixos via the home-manager module, since there are multiple users with different shortcuts on the system, but after binding the startup of an application to a shortcut, it does not start and the following error appears in the service logs.
```
Jan 01 19:30:46 nix xremap[595413]: [2024-01-01T16:30:46Z DEBUG xremap::action_dispatcher] Running command: ["pavucontrol"]
Jan 01 19:30:46 nix xremap[650912]: [2024-01-01T16:30:46Z ERROR xremap::action_dispatcher] Error running command: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```
I have tried launching applications with full paths, but rofi still cannot launch any application if it is launched via a shortcut.
There is my configuration:
```nix
{ pkgs, inputs, ... }:
let
  shell = script: ["${pkgs.writeShellScriptBin "script" script}/bin/script"];
in {
  imports = [
    inputs.xremap-flake.homeManagerModules.default
  ];

  services.xremap = {
    withWlroots = true;
    deviceName = "ROYUAN EPOMAKER TH96 Pro";
    config = {
      keymap = [
        {
          name = "media control";
          remap = {
            mute = {
              # works
              launch = shell "${pkgs.wireplumber}/bin/wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle";
            };
          };
        }
        {
          name = "apps";
          remap = {
            alt-r = {
              # works, but i cant launch any app
              launch = shell "${pkgs.killall}/bin/killall rofi || ${pkgs.rofi-wayland}/bin/rofi -show drun";
            };
            alt-f = {
              # doesnt work
              launch = [ "pavucontrol" ];
            };
          };
        }
      ];
    };
  };
}
```
Also, is there any way to enable the service declaratively? In my case, the xremap service is disabled by default and I have to start it manually. Thanks in advance!

**Comment by VTimofeenko** [comment]
Two things here:

# Binaries cannot be found

The "No such file or directory" is most likely due to differences in $PATH variable between the user and the service. With this xremap mapping:

```nix
      {
        name = "Remap hyper key";
        remap = {
          "F18-a" = {
            launch = [ "pavucontrol" ];
          };
        };
      }
```

And pavucontrol installed only for my user:

```shell
$ which pavucontrol
/etc/profiles/per-user/<USERNAME>/bin/pavucontrol
```

This propagated the PATH variable into xremap service:
```nix
{
  systemd.user.services.xremap.serviceConfig.Environment = [
    "PATH=/etc/profiles/per-user/<USERNAME>/bin"
  ];
}
```

and I was able to launch pavucontrol by hitting F18(actually, CapsLock)+a.

I am using NixOS module though. For home-manager it should be something like this:

```nix
{
  systemd.user.services.mbsync.Service.Environment = [
    "PATH=/etc/profiles/per-user/<USERNAME>/bin"
  ];
}
```

Don't forget to restart the `xremap.service` after switching as automatic service restart is not yet implemented (#49)

# Enabling the service declaratively

`xremap.service` is wantedby graphical-session.target. Some DEs do not start that systemd user target automatically.

1. Which DE are you using?
2. What is the output of `systemctl --user status graphical-session.target` immediately after you log in?

**Comment by TalkierTick9904** [comment]
Thank you for your reply! I added this to my configuration and now every application runs without error:
```nix
systemd.user.services.xremap.Service.Environment = lib.mkForce [
  "PATH=/run/current-system/sw/bin:/etc/profiles/per-user/<USERNAME>/bin"
];
```
I'm using hyprland and here is the status of graphical-session.target at login:
```
graphical-session.target - Current graphical user session
     Loaded: loaded (/etc/systemd/user/graphical-session.target; static)
     Active: inactive (dead)
       Docs: man:systemd.special(7)
```

**Comment by VTimofeenko** [comment]
> `"PATH=/run/current-system/sw/bin:/etc/profiles/per-user/<USERNAME>/bin"`

Yeah, that should work for most applications. I would recommend binding keys to package references rather than to strings of executables. As long as you're using the same instance of `pkgs` across your flake, there would be no duplication. I.e. instead of:

```nix
{"F18-a" = {
            launch = [ "pavucontrol" ];
          };}
```

do

```nix
{"F18-a" = {
            launch = [ "${lib.getExe' pkgs.pavucontro "pavucontrol"l} ];
          };}
```

Otherwise if the package was uninstalled - xremap would fail with the same error 2.

I am also using hyprland from their flake's module with (`systemdIntegration = true;
`), and graphical-session.target auto-starts for me. Try that setting or use some incantation of exec-once. For example I have at the beginning of hyprland.conf:

```
exec-once=/nix/store/ldll0l8a0ax6l6l2hsly0h6hijh180gd-dbus-1.14.10/bin/dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY HYPRLAND_INSTANCE_SIGNATURE XDG_CURRENT_DESKTOP && systemctl --user start hyprland-session.target
```

**Comment by VTimofeenko** [comment]
Notes to self:
1. The binds `$PATH` problem needs to be documented/added as a feature?
2. Graphical-session.target setup needs to be documented

**Comment by TalkierTick9904** [comment]
Thanks! I reinstalled hyprland as flake and now it starts with log in!

**Comment by TalkierTick9904** [comment]
Hi! sorry to bother you, but I noticed that applications running via xremap have a different cursor size, I think it's related to some system variable. Is there any way to pass xremap all system variables?

**Comment by VTimofeenko** [comment]
It's probably 

```
env = XCURSOR_SIZE,<VALUE>
```

that's set in hyprland but not propagated through to xremap. 

You can propagate environment variables to systemd through `systemctl --user import-environment` or use EnvironmentFile setting on the service. But IMO this is prone to racing or inconsistencies.

I think a better approach would be to bind a button in xremap to `hyprctl dispatch exec <binary>`. That way hyprland would be the central source of truth for variables like this.

**Comment by TalkierTick9904** [comment]
Thanks for the hyprctl example! I rewrote my config with that in mind, and overriding the PATH variable is no longer needed. So the key bindings for running applications through the home manager module on hyprland should look something like this:
```nix
{ pkgs, inputs, lib, ... }:
let
  shell = script: lib.strings.splitString " " "hyprctl dispatch exec ${lib.getExe' (pkgs.writeShellScriptBin "script" script) "script"}";
in {
  imports = [
    inputs.xremap.homeManagerModules.default
  ];

  services.xremap = {
    withWlroots = true;
    deviceName = "device name";
    config = {
      keymap = [
        {
          name = "example";
          remap = {
            ctrl-mute = {
              launch = shell "${lib.getExe' pkgs.killall "killall"} rofi || ${lib.getExe' pkgs.rofi-wayland "rofi"} -show drun";
            };
          };
        }
      ];
    };
  };
}
```

**Comment by ValynTyler** [comment]
I have the same issue. NixOS + GNOME. I tried the solutions here and I can't get it to work.
